# Generated by Django 4.2.21 on 2025-05-07 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="ชื่อที่ผู้ใช้ตั้งเองสำหรับสเปคนี้ (เช่น 'PC เล่นเกมสุดคุ้ม')", max_length=200, null=True)),
                ('build_details', models.JSONField(help_text='รายละเอียดสเปคคอมพิวเตอร์ที่ได้จาก Gemini (JSON format)')),
                ('source_prompt_details', models.JSONField(blank=True, help_text='รายละเอียด input เดิมของผู้ใช้ (งบ, เกม, ส่วนที่ต้องการ) ที่ใช้สร้างสเปคนี้ (JSON format)', null=True)),
                ('user_notes', models.TextField(blank=True, help_text='บันทึกส่วนตัวของผู้ใช้เกี่ยวกับสเปคนี้', null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_specs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
